### PR TITLE
Hubbard model: Example of real/imaginary time propagation

### PR DESCRIPTION
**Pull request by ybarlev**
Hello,

Currently there is very little documentation and examples of the Hubbard model. And there is no explanation about the operators: A, F and Cdn and Cup.

After struggling with this by myself, I have created an example file, which briefly explains the roles of the different operators, and the way the kinetic term of the Hubbard model should be treated.

The example file could be used as a template for more sophisticated programs.

Hope it helps,
Yevgeny.

### CODE REVIEW

**Comment by emstoudenmire** [comment]
Hi Yengeny - I didn't mean to neglect this issue for so long. Please send along the example file if you still want to and I will try to incorporate it into our docs.

**Comment by ybarlev** [comment]
No worries. You have more urgent matters. Can't you see my pull request on
this issue?
I had to close my pull-request since I couldn't proceed with the new one
for some reason.
I am quite new with this.

**Comment by emstoudenmire** [comment]
I looked to see the changed files related to this pull request, but they seem to be missing. Clicking on the Files Changed tab I only see your most recent pull request related to the periodic BC's

**Comment by ybarlev** [comment]
It appears that by closing the pull request I have undone the changes, and cannot find them.
It is however not so important now, since by you have a nice explanation about fermions in your docs.

**Comment by emstoudenmire** [comment]
Ok sorry again about not replying sooner. We are also planning to add some more docs soon on the definitions of the different operators in the various SiteSet classes (e.g. Hubbard, SpinHalf, etc.)

**Pull request closed without merging**
