### PR TITLE
Fixes Sweeps Bug and Implemented Read/Write for QCombine

### PR DESCRIPTION
**Pull request by lfrahm**
Hi, 
I was able to fix the problem I was describing here: http://itensor.org/support/489/segmentation-fault-when-using-combiner

I implemented the necessary read/write methods and now it works. I tried to be as consistent with your style as possible. I hope you can merge it into your repository. 

I also fixed another problem with the read/write of Sweeps. 

If you have questions or comments, just let me know. 

Best,
Lars

### CODE REVIEW

**Comment by emstoudenmire** [comment]
Hi Lars,
Really glad you found how to fix your issue and I'd like to merge this. One question before I do though: what was the issue with the Sweeps read/write code? Was the use of auto breaking things?

**Comment by emstoudenmire** [comment]
Thanks for the patch. I just merged it. Major oversight on my part that QCombiner storage didn't have read/write support! I put in a slightly newer implementation of the Sweeps read/write code

**Comment by lfrahm** [comment]
Hi Miles,
Thanks for merging and updating the read/write code for Sweeps. I had the issue that after reading Sweeps from binary I got segmentation faults. Your update fixes that too. Thanks. 

By the way, big thanks for the MPI support you added recently. I think that's an awesome new feature. I extended (will extend further) your code a little bit here: https://github.com/lfrahm/MOL/blob/master/src/parallel_extended.h If you are interested I can prepare a pull request for that too. 

I have another problem with the combiner. Unfortunately I am unable to pin it down to an easy reproducible example yet. But I keep investigating it and will let you know as soon I can clearly state what the problem is. 

Thanks again, 
Lars

**Comment by emstoudenmire** [comment]
Hi Lars,
Glad the MPI code is helpful. I found that it was a much needed wrapper around the MPI C interface which is itself pretty nice, but benfited from taking advantage of C++ templates and also from some logic about breaking up data into smaller chunks when sending and receiving.

I'd be glad if you prepare a pull request for those additional Environment methods. What does scatterVector do by the way?

A colleague also filed a bug report with me about IQTensor combiners. So I will look into that. Perhaps it is the same as the one you are finding? I don't know but please let me know more about the bug you are seeing.

**Pull request merged**
